# VacationPy
----

#### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [2]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from api_keys import g_key

AIzaSyCi670bGpAfP3Y7o2bZM1TKeYq0Ew_0lMY

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [15]:
#import "clean cities csv"
file = "../output_data/clean_cities_data.csv"
weather_df = pd.read_csv(file)
weather_df

,City Name,Latitude,Longitude,Temperature,Humidity,Cloudiness,Windspeed,Date
0,Yumen,40.28,97.20,296.98,36,30,4.54,2020-07-14 02:01:18
1,Yellowknife,62.46,-114.35,287.09,100,90,7.70,2020-07-14 02:01:18
2,Dunmore Town,25.50,-76.65,302.11,77,100,4.50,2020-07-14 02:01:19
3,Nyagan,62.14,65.39,287.12,55,25,1.97,2020-07-14 02:01:19
4,Pemangkat,1.17,108.97,296.95,95,100,5.36,2020-07-14 02:01:19
...,...,...,...,...,...,...,...,...
67,Calama,-22.47,-68.93,282.15,4,1,1.00,2020-07-14 02:00:02
68,Tasiilaq,65.61,-37.64,279.15,81,66,0.50,2020-07-14 02:01:28
69,Hong Kong,22.29,114.16,304.61,74,29,3.58,2020-07-14 01:59:09
70,Svecha,58.28,47.52,292.90,97,98,3.46,2020-07-14 02:01:28
71,Shelburne,44.08,-80.20,291.33,77,90,2.10,2020-07-14 02:00:18

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [16]:
#access maps with unique API key
gmaps.configure(api_key = g_key)

In [36]:
#create coordinates
records = weather_df[["Latitude", "Longitude"]].to_records(index=False)
coordinates = list(records)
weights = weather_df['Humidity']
#customize map
figure_layout = {'width': '500px', 'margin': '0 auto 0 auto'}
fig = gmaps.figure(layout=figure_layout)
heat_layer = gmaps.heatmap_layer(coordinates, weights = weights)

#assign marker layer
fig.add_layer(heat_layer)
fig

Figure(layout=FigureLayout(height='420px', margin='0 auto 0 auto', width='500px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [39]:
#drop null values
vacation_df = weather_df.dropna(axis=1)
vacation_df

,City Name,Latitude,Longitude,Temperature,Humidity,Cloudiness,Windspeed,Date
0,Yumen,40.28,97.20,296.98,36,30,4.54,2020-07-14 02:01:18
1,Yellowknife,62.46,-114.35,287.09,100,90,7.70,2020-07-14 02:01:18
2,Dunmore Town,25.50,-76.65,302.11,77,100,4.50,2020-07-14 02:01:19
3,Nyagan,62.14,65.39,287.12,55,25,1.97,2020-07-14 02:01:19
4,Pemangkat,1.17,108.97,296.95,95,100,5.36,2020-07-14 02:01:19
...,...,...,...,...,...,...,...,...
67,Calama,-22.47,-68.93,282.15,4,1,1.00,2020-07-14 02:00:02
68,Tasiilaq,65.61,-37.64,279.15,81,66,0.50,2020-07-14 02:01:28
69,Hong Kong,22.29,114.16,304.61,74,29,3.58,2020-07-14 01:59:09
70,Svecha,58.28,47.52,292.90,97,98,3.46,2020-07-14 02:01:28
71,Shelburne,44.08,-80.20,291.33,77,90,2.10,2020-07-14 02:00:18

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [42]:
#add hotel to weather_df
hotel_name = []
weather_df["Hotel Name"] = ""

#set parameters for searching
params = {"coordinates": coordinates, "key": g_key}
base_url = "https://maps.googleapis.com/maps/api/geocode/json"

,City Name,Latitude,Longitude,Temperature,Humidity,Cloudiness,Windspeed,Date,Hotel Name
0,Yumen,40.28,97.20,296.98,36,30,4.54,2020-07-14 02:01:18,
1,Yellowknife,62.46,-114.35,287.09,100,90,7.70,2020-07-14 02:01:18,
2,Dunmore Town,25.50,-76.65,302.11,77,100,4.50,2020-07-14 02:01:19,
3,Nyagan,62.14,65.39,287.12,55,25,1.97,2020-07-14 02:01:19,
4,Pemangkat,1.17,108.97,296.95,95,100,5.36,2020-07-14 02:01:19,
...,...,...,...,...,...,...,...,...,...
67,Calama,-22.47,-68.93,282.15,4,1,1.00,2020-07-14 02:00:02,
68,Tasiilaq,65.61,-37.64,279.15,81,66,0.50,2020-07-14 02:01:28,
69,Hong Kong,22.29,114.16,304.61,74,29,3.58,2020-07-14 01:59:09,
70,Svecha,58.28,47.52,292.90,97,98,3.46,2020-07-14 02:01:28,
71,Shelburne,44.08,-80.20,291.33,77,90,2.10,2020-07-14 02:00:18,

In [43]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

NameError: name 'hotel_df' is not defined

In [ ]:
# Add marker layer ontop of heat map


# Display figure